// Copyright © 2025 CIF Foundation
//
// SPDX-License-Identifier: Apache-2.0
//
// Template for CIF plugin gRPC services. You may copy and modify this file
// for use in your own CIF plugins. See LICENSE for full license terms.

syntax = "proto3";

import "cif_common.proto";
//The CIF protos are installed in the default CIF data directory.  On Windows this is C:/Users/Public/Documents/CIF/protos
//When generating new gRPC server/client code this directory needs to be provided as an Import path

package cif.template;

// This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

service Template {
  rpc SetNumeric (Numeric) returns (cif.common.Status) {}
  rpc GetResult (cif.common.Empty) returns (Result) {}
  rpc GetStatistics (cif.common.Empty) returns (Statistics) {}
}

message Numeric {
   int32 numeric = 1;
}

message Result {
   int32 result = 1;
}

message Statistics {
   uint64 iterations = 1;
}